### ISSUE TITLE
Segmentation fault (core dumped) - With Undulator

### ISSUE THREAD

**Issue by SergioLordano** [oasys-lnls-kit/OASYS1-LNLS-ShadowOui#1]
Calculating the flux of undulator beamlines with Flux widget, I got this error while SRW was running:

```
Segmentation fault (core dumped)
```

It appears that the problem is which srwlib it was calling. In my case I have my own SRW installation and `$PYTHONPATH` is set in `.bashrc` file, pointing to my own installation. 
SOLUTION: remove the `$PYTHONPATH` line in the `.bashrc` and restart the computer. 
After that, everything runs fine again. Without setting `$PYTHONPATH` in the `.bashrc`, it is also possible to include the SRW path in the simulation python script with:
```
import sys
sys.path.append('/path/to/srwlib')
```

**Comment by lucarebuffi** [comment]
Good to know...
